### ISSUE TITLE
This project only contains the testing phase?

### ISSUE THREAD

**Issue by jiamingzhang94** [ronny3050/AdvFaces#1]
I ran the project. Is the pre-trained model a generator in GAN? And Is there a training phase code?
Thanks！

**Comment by ronny3050** [comment]
Currently, the pre-trained model generates the adversarial faces (the generator in GAN). I will release the training code as well next week since I am traveling. Thank you!

**Comment by ronny3050** [comment]
Hi! The code is updated now to include the training phase as well.

Please let me know if there are any issues and/or if I can improve the repo in any way. 

Thanks!
