### ISSUE TITLE
ValueError: Cannot initialize dataset from path 

### ISSUE THREAD

**Issue by liangjie15** [ronny3050/AdvFaces#2]
Hi:
I have a question that needs your help.Thanks
 File "/data6/liangjie/project/AdvFaces-master/utils/dataset.py", line 106, in init_from_path
    It should be either a folder, .txt or .hdf5 file' % path)
ValueError: Cannot initialize dataset from path: /D:/2021plan/Advfaces/AdvFaces-master/CASIA-WebFace_aligned_160
                It should be either a folder, .txt or .hdf5 file
I think it should be a data set problem, but I don't know how to solve it.

**Comment by ronny3050** [comment]
Hi @liangjie15! Seems like the dataset path `` /D:/2021plan/Advfaces/AdvFaces-master/CASIA-WebFace_aligned_160`` is wrong.  

Maybe it is ``D:/2021plan/Advfaces/AdvFaces-master/CASIA-WebFace_aligned_160``

**Comment by liangjie15** [comment]
thank you very much.
But the problem still exists.Can you share your data set?

**Comment by ronny3050** [comment]
Hi! The dataset we use is CASIA-WebFace for training. You will definitely be able to find links online.

In case not, let me know.
