### ISSUE TITLE
 'NoneType' object has no attribute 'value'

### ISSUE THREAD

**Issue by emnab** [ronny3050/AdvFaces#8]
hi, I have an error while running the training, I use TF2.4 (i upgraded the code ) and GPU, Can you help me, please?
(None, 160, 160, 3)
/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1719: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
Traceback (most recent call last):
  File "train.py", line 178, in <module>
    main(args)
  File "train.py", line 68, in main
    network.initialize(config, trainset.num_classes)
  File "/kaggle/working/advfaces.py", line 68, in initialize
    self.perturb, self.G = self.generator(self.images)
  File "architectures/advfaces.py", line 89, in generator

**Comment by ronny3050** [comment]
Please post the entire output/error.
